import { NavigatorScreenParams } from "@react-navigation/native";
import { BottomTabParamList } from "./BottomTabParamList";
import { DrawerNavigationProp } from '@react-navigation/drawer';
import { StackNavigationProp } from "@react-navigation/stack";

export type RootStackParamList = {
    DrawerNavigation: NavigatorScreenParams<BottomTabParamList>;
    openDrawer:undefined;
    Demo: undefined;
    Confirmation : undefined;
    Plans: undefined;
    PlanDetails: undefined;
    ChooseLanguage: undefined;
    QrCodeScanner: undefined;
    WelCome: undefined;
    SignUp: undefined;
    SingIn: undefined;
    Onboarding: undefined;
    Services : undefined;
    Login: undefined;
    Register: undefined;
    ForgotPassword: undefined;
    OTPAuthentication: undefined;
    EmailVerify: undefined;
    NewPassword: undefined;
    Rewards: undefined;
    ResetPassword: undefined;
    Settings: undefined;
    ChangePassword: undefined;
    TwoStepAuthentication: undefined;
    BottomNavigation: undefined;
    Singlechat: undefined;
    Chat: undefined;
    Support: undefined;
    History: undefined;
    Verification: undefined;
    Call: undefined;
    EditProfile: undefined;
    Trackorder: undefined;
    Products: undefined;
    Language: undefined;
    MyCart: undefined;
    Category: undefined;
    Notifications: undefined;
    Questions: undefined;
    ProductsDetails: undefined;
    Writereview: undefined;
    Profile: undefined;
    Wishlist: undefined;
    Search: undefined;
    Components: undefined;
    Coupons: undefined;
    DeliveryAddress: undefined;
    Checkout: undefined;
    Addcard: undefined;
    Payment: undefined;
    AddDeliveryAddress: undefined;
    Myorder: undefined;
    Notification: undefined;
    Home: undefined;
    Accordion: undefined;
    BottomSheet: undefined;
    ModalBox: undefined;
    Buttons: undefined;
    Badges: undefined;
    Charts: undefined;
    Headers: undefined;
    lists: undefined;
    Pricings: undefined;
    DividerElements: undefined;
    Snackbars: undefined;
    Socials: undefined;
    Swipeable: undefined;
    Tabs: undefined;
    Tables: undefined;
    Toggles: undefined;
    Inputs: undefined;
    Footers: undefined;
    TabStyle1: undefined;
    TabStyle2: undefined;
    TabStyle3: undefined;
    TabStyle4: undefined;

};
export type DrawerParamList = {
    HomeStack: NavigatorScreenParams<RootStackParamList>; 
  };
  export type HomeScreenProps = {
    navigation: DrawerNavigationProp<DrawerParamList, 'HomeStack'> & StackNavigationProp<RootStackParamList, 'Home'>;
  };